# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./output:/usr/src/app/output
